
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightIMPLIESleftORleftANDrightNOTAND CONST DOT EQ GEQ GREATER IMPLIES LEQ LESS LPAREN NOT OP_EXISTS OP_FORALL OR PROP RELEASE RPAREN TOP UNTILexpression : expression AND expression\n| expression OR expression\n| expression IMPLIES expressionexpression : NOT expressionexpression : LPAREN expression RPARENexpression : TOPexpression : PROPexpression : PROP DOT expressionexpression : PROP LEQ CONST\n| PROP LESS CONST\n| PROP GEQ CONST\n| PROP GREATER CONST\n| PROP EQ CONSTexpression : OP_EXISTS LPAREN expression UNTIL expression RPAREN\n| OP_EXISTS LPAREN expression RELEASE expression RPAREN\n| OP_FORALL LPAREN expression UNTIL expression RPAREN\n| OP_FORALL LPAREN expression RELEASE expression RPAREN\n'
    
_lr_action_items = {'NOT':([0,2,3,8,9,10,13,19,20,33,34,35,36,],[2,2,2,2,2,2,2,2,2,2,2,2,2,]),'LPAREN':([0,2,3,6,7,8,9,10,13,19,20,33,34,35,36,],[3,3,3,19,20,3,3,3,3,3,3,3,3,3,3,]),'TOP':([0,2,3,8,9,10,13,19,20,33,34,35,36,],[4,4,4,4,4,4,4,4,4,4,4,4,4,]),'PROP':([0,2,3,8,9,10,13,19,20,33,34,35,36,],[5,5,5,5,5,5,5,5,5,5,5,5,5,]),'OP_EXISTS':([0,2,3,8,9,10,13,19,20,33,34,35,36,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'OP_FORALL':([0,2,3,8,9,10,13,19,20,33,34,35,36,],[7,7,7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,4,5,11,21,22,23,24,25,26,27,28,29,30,41,42,43,44,],[0,-6,-7,-4,-1,-2,-3,-5,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,]),'AND':([1,4,5,11,12,21,22,23,24,25,26,27,28,29,30,31,32,37,38,39,40,41,42,43,44,],[8,-6,-7,-4,8,-1,8,8,-5,8,-9,-10,-11,-12,-13,8,8,8,8,8,8,-14,-15,-16,-17,]),'OR':([1,4,5,11,12,21,22,23,24,25,26,27,28,29,30,31,32,37,38,39,40,41,42,43,44,],[9,-6,-7,-4,9,-1,-2,9,-5,9,-9,-10,-11,-12,-13,9,9,9,9,9,9,-14,-15,-16,-17,]),'IMPLIES':([1,4,5,11,12,21,22,23,24,25,26,27,28,29,30,31,32,37,38,39,40,41,42,43,44,],[10,-6,-7,-4,10,-1,-2,10,-5,10,-9,-10,-11,-12,-13,10,10,10,10,10,10,-14,-15,-16,-17,]),'RPAREN':([4,5,11,12,21,22,23,24,25,26,27,28,29,30,37,38,39,40,41,42,43,44,],[-6,-7,-4,24,-1,-2,-3,-5,-8,-9,-10,-11,-12,-13,41,42,43,44,-14,-15,-16,-17,]),'UNTIL':([4,5,11,21,22,23,24,25,26,27,28,29,30,31,32,41,42,43,44,],[-6,-7,-4,-1,-2,-3,-5,-8,-9,-10,-11,-12,-13,33,35,-14,-15,-16,-17,]),'RELEASE':([4,5,11,21,22,23,24,25,26,27,28,29,30,31,32,41,42,43,44,],[-6,-7,-4,-1,-2,-3,-5,-8,-9,-10,-11,-12,-13,34,36,-14,-15,-16,-17,]),'DOT':([5,],[13,]),'LEQ':([5,],[14,]),'LESS':([5,],[15,]),'GEQ':([5,],[16,]),'GREATER':([5,],[17,]),'EQ':([5,],[18,]),'CONST':([14,15,16,17,18,],[26,27,28,29,30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,8,9,10,13,19,20,33,34,35,36,],[1,11,12,21,22,23,25,31,32,37,38,39,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND expression','expression',3,'p_expression_binary','parser.py',150),
  ('expression -> expression OR expression','expression',3,'p_expression_binary','parser.py',151),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_binary','parser.py',152),
  ('expression -> NOT expression','expression',2,'p_expression_not','parser.py',156),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',160),
  ('expression -> TOP','expression',1,'p_expression_top','parser.py',164),
  ('expression -> PROP','expression',1,'p_expression_atomic','parser.py',168),
  ('expression -> PROP DOT expression','expression',3,'p_expression_freeze','parser.py',175),
  ('expression -> PROP LEQ CONST','expression',3,'p_expression_time','parser.py',182),
  ('expression -> PROP LESS CONST','expression',3,'p_expression_time','parser.py',183),
  ('expression -> PROP GEQ CONST','expression',3,'p_expression_time','parser.py',184),
  ('expression -> PROP GREATER CONST','expression',3,'p_expression_time','parser.py',185),
  ('expression -> PROP EQ CONST','expression',3,'p_expression_time','parser.py',186),
  ('expression -> OP_EXISTS LPAREN expression UNTIL expression RPAREN','expression',6,'p_expression_opacity','parser.py',195),
  ('expression -> OP_EXISTS LPAREN expression RELEASE expression RPAREN','expression',6,'p_expression_opacity','parser.py',196),
  ('expression -> OP_FORALL LPAREN expression UNTIL expression RPAREN','expression',6,'p_expression_opacity','parser.py',197),
  ('expression -> OP_FORALL LPAREN expression RELEASE expression RPAREN','expression',6,'p_expression_opacity','parser.py',198),
]
