
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightNOTAND CONST EVENTUALLY EXIST FORALL GEQ GLOBALLY GREATER IMPLIES LEQ LESS LPAREN NOT OR PROP RPAREN TIME_SEP UNTILexpression : expression AND expression\n| expression OR expression\n| expression IMPLIES expressionexpression : FORALL expression UNTIL expression\n| EXIST expression UNTIL expressionexpression : FORALL GLOBALLY expression\n| FORALL EVENTUALLY expression\n| EXIST GLOBALLY expression\n| EXIST EVENTUALLY expressionexpression : NOT expressionexpression : LPAREN expression RPARENexpression : PROP TIME_SEP expressionexpression : LPAREN expression RPAREN TIME_SEP expressionexpression : PROPexpression : PROP LEQ CONST\n| PROP LESS CONST\n| PROP GEQ CONST\n| PROP GREATER CONST\n'
    
_lr_action_items = {'FORALL':([0,2,3,4,5,7,8,9,11,12,14,15,18,26,29,40,],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,]),'EXIST':([0,2,3,4,5,7,8,9,11,12,14,15,18,26,29,40,],[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,]),'NOT':([0,2,3,4,5,7,8,9,11,12,14,15,18,26,29,40,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'LPAREN':([0,2,3,4,5,7,8,9,11,12,14,15,18,26,29,40,],[5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,]),'PROP':([0,2,3,4,5,7,8,9,11,12,14,15,18,26,29,40,],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'$end':([1,6,16,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,41,],[0,-14,-10,-1,-2,-3,-6,-7,-8,-9,-11,-12,-15,-16,-17,-18,-4,-5,-13,]),'AND':([1,6,10,13,16,17,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,41,],[7,-14,7,7,-10,7,7,7,7,7,7,7,7,-11,7,-15,-16,-17,-18,7,7,7,]),'OR':([1,6,10,13,16,17,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,41,],[8,-14,8,8,-10,8,8,8,8,8,8,8,8,-11,8,-15,-16,-17,-18,8,8,8,]),'IMPLIES':([1,6,10,13,16,17,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,41,],[9,-14,9,9,-10,9,9,9,9,9,9,9,9,-11,9,-15,-16,-17,-18,9,9,9,]),'GLOBALLY':([2,3,],[11,14,]),'EVENTUALLY':([2,3,],[12,15,]),'TIME_SEP':([6,32,],[18,40,]),'UNTIL':([6,10,13,16,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,41,],[-14,26,29,-10,-1,-2,-3,-6,-7,-8,-9,-11,-12,-15,-16,-17,-18,-4,-5,-13,]),'RPAREN':([6,16,17,23,24,25,27,28,30,31,32,33,34,35,36,37,38,39,41,],[-14,-10,32,-1,-2,-3,-6,-7,-8,-9,-11,-12,-15,-16,-17,-18,-4,-5,-13,]),'LEQ':([6,],[19,]),'LESS':([6,],[20,]),'GEQ':([6,],[21,]),'GREATER':([6,],[22,]),'CONST':([19,20,21,22,],[34,35,36,37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,4,5,7,8,9,11,12,14,15,18,26,29,40,],[1,10,13,16,17,23,24,25,27,28,30,31,33,38,39,41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND expression','expression',3,'p_expression_binary','parser.py',125),
  ('expression -> expression OR expression','expression',3,'p_expression_binary','parser.py',126),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_binary','parser.py',127),
  ('expression -> FORALL expression UNTIL expression','expression',4,'p_expression_ternary','parser.py',131),
  ('expression -> EXIST expression UNTIL expression','expression',4,'p_expression_ternary','parser.py',132),
  ('expression -> FORALL GLOBALLY expression','expression',3,'p_expression_unary','parser.py',136),
  ('expression -> FORALL EVENTUALLY expression','expression',3,'p_expression_unary','parser.py',137),
  ('expression -> EXIST GLOBALLY expression','expression',3,'p_expression_unary','parser.py',138),
  ('expression -> EXIST EVENTUALLY expression','expression',3,'p_expression_unary','parser.py',139),
  ('expression -> NOT expression','expression',2,'p_expression_not','parser.py',143),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',147),
  ('expression -> PROP TIME_SEP expression','expression',3,'p_expression_clock_prop','parser.py',151),
  ('expression -> LPAREN expression RPAREN TIME_SEP expression','expression',5,'p_expression_clock_group','parser.py',155),
  ('expression -> PROP','expression',1,'p_expression_prop','parser.py',160),
  ('expression -> PROP LEQ CONST','expression',3,'p_expression_time','parser.py',164),
  ('expression -> PROP LESS CONST','expression',3,'p_expression_time','parser.py',165),
  ('expression -> PROP GEQ CONST','expression',3,'p_expression_time','parser.py',166),
  ('expression -> PROP GREATER CONST','expression',3,'p_expression_time','parser.py',167),
]
